export enum ACTION_SCORE {
  NORMAL_ACTION = 0,
  OBSTACLE_DETECTED = 9000,

  FOUND_FOOD_NEARBY = 200,
  SMALL_BODY = 100,

  GO_TO_PLAYER_DEFAULT = -40,
  BECOME_AGGRESIVE = 440,
  AGGRESIVE_ON_COOLDOWN = -360,
}
